# Generates git_version.h from the actual git state, on every build.
#
# Ported from the 10.8.0 fork (standalone/cmake/GenGitVersion.cmake). Upstream commits a
# placeholder src/core/git_version.h (GIT_SHA "unknown") that only its release CI substitutes, so
# every local build logs "Rev. 9999 (unknown)" and an on-device log cannot tell you whether a
# deploy actually landed. The workspace deploy-verification rule depends on this stamp being real.
#
# Unlike 10.8.0 this writes into the BUILD tree, never over the committed placeholder: that file is
# tracked here, so rewriting it would dirty the tree and feed back into the fingerprint below.
# src/core/vpversion.h includes <git_version.h> (angle brackets) so the generated copy, whose
# directory is prepended to the include path, wins over the placeholder.
#
# GIT_SHA carries a fingerprint of any uncommitted changes ("<sha>+<hash>"), because working-tree
# edits otherwise keep the committed SHA and two different test builds look identical in the log.
# GIT_REVISION is deliberately left at 9999: it is baked into the tournament-file format.
#
# Usage:
#   cmake -DSRC=<source dir> -DOUT=<path to git_version.h> -P GenGitVersion.cmake

find_package(Git QUIET)

set(_sha "unknown")

if(GIT_FOUND)
   execute_process(
      COMMAND ${GIT_EXECUTABLE} rev-parse --short=7 HEAD
      WORKING_DIRECTORY "${SRC}"
      OUTPUT_VARIABLE _sha
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET)

   if(_sha STREQUAL "")
      set(_sha "unknown")
   endif()

   # Fingerprint the working tree. The generated header lives in the build tree, so it cannot feed
   # back into its own hash.
   execute_process(
      COMMAND ${GIT_EXECUTABLE} diff HEAD
      WORKING_DIRECTORY "${SRC}"
      OUTPUT_VARIABLE _diff
      ERROR_QUIET)

   if(NOT _diff STREQUAL "")
      string(MD5 _diff_hash "${_diff}")
      string(SUBSTRING "${_diff_hash}" 0 4 _diff_hash)
      set(_sha "${_sha}+${_diff_hash}")
   endif()
endif()

set(_content
"#ifndef _GIT_VERSION_H_
#define _GIT_VERSION_H_

// GENERATED by make/GenGitVersion.cmake -- do not edit, do not commit.

#define GIT_REVISION 9999
#define GIT_SHA      \"${_sha}\"

#endif
")

# Only rewrite when it actually changed, so we do not force a rebuild of everything that pulls in
# vpversion.h on every single build.
set(_existing "")
if(EXISTS "${OUT}")
   file(READ "${OUT}" _existing)
endif()

if(NOT _existing STREQUAL _content)
   file(WRITE "${OUT}" "${_content}")
   message(STATUS "git_version.h: GIT_SHA=${_sha}")
endif()
